### ISSUE TITLE
Why do we have to click search twice?

### ISSUE THREAD

**Issue by joeromine** [Vets-Who-Code/march2021#376]

**Comment by sml0291** [comment]
I found API takes time to load up, which makes the array "job" empty (and causes the issue of clicking twice to see the data). The easiest solution I found is to wait for a second by using "setTimeout", but I'm looking into "async/await", which seems to be a superior solution. If I can't figure out how to use "async/await", I will add "setTimeout" for a temporary solution.

**Comment by sml0291** [comment]
"async/await" turned out that it can be applied to functions only (https://stackoverflow.com/questions/21518381/proper-way-to-wait-for-one-function-to-finish-before-continuing), but when I tried to add "async" to "function submitButtonEvent(event)", it didn't work. I will simply use "setTimeout" if there is no other thoughts.
